plugins {
    id 'com.android.application'
}

android {
    namespace = 'com.gina.pomodoro'
    compileSdk = 36

    signingConfigs {
        stableDebug {
            storeFile = file('pomodoro-debug.jks')
            storePassword = 'tomato-dev'
            keyAlias = 'pomodoro'
            keyPassword = 'tomato-dev'
        }
    }

    defaultConfig {
        applicationId = 'com.gina.pomodoro'
        minSdk = 26
        targetSdk = 36
        versionCode = 5
        versionName = '1.4'
    }

    buildTypes {
        debug {
            signingConfig = signingConfigs.stableDebug
        }
    }
}
